name: Proxy Checker

on:
  workflow_dispatch:

jobs:
  check-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run proxy checker script
        run: |
          node prx-checker.js

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add prxip.txt prxip.json
          git commit -m "✅ Update proxy results [auto]" || echo "No changes to commit"
          git push
